version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
      - "3306:3306"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "./:/var/www/html/custom/plugins/MltisafeMultiSafepayPayment/"
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.0
    entrypoint: "sh /entrypoint-multisafepay.sh ${APP_SUBDOMAIN} ${EXPOSE_HOST}"
  expose:
    depends_on:
      - app
    build: https://github.com/beyondcode/expose.git
    entrypoint: ["/bin/sh", "-c" , "/src/expose token ${EXPOSE_TOKEN} && sed -i -E \"s/'dns'\\s?=>\\s?'.*'/'dns' => true/g\" /root/.expose/config.php  && /src/expose share app --server-host=${EXPOSE_HOST} --subdomain=${APP_SUBDOMAIN}"]
    ports:
      - 4040:4040
