name: Build
on:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  integration_tests:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: shopware
        ports:
          - 3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: [ '7.4' ]
        shopware_version: [ '5.6' ]
    name: Integration test - Php version ${{ matrix.php_version }} with Shopware ${{ matrix.shopware_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install php
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php_version }}
          tools: composer
          coverage: none
      - name: Install Shopware
        run: |
          git clone -b ${{ matrix.shopware_version }} --depth=1 https://github.com/shopware/shopware.git /tmp/shopware
          cd /tmp/shopware
          php psh.phar init --DB_HOST="127.0.0.1" --DB_USER="root" --DB_PASSWORD="password" --DB_PORT=${{ job.services.mysql.ports['3306'] }}
      - name: Install MultiSafepay Plugin
        run: |
          mkdir -p /tmp/shopware/custom/plugins/MltisafeMultiSafepayPayment
          mv * /tmp/shopware/custom/plugins/MltisafeMultiSafepayPayment
          cd /tmp/shopware/custom/plugins/MltisafeMultiSafepayPayment
          composer install --no-dev
          cd /tmp/shopware
          php /tmp/shopware/bin/console sw:plugin:install --clear-cache --activate MltisafeMultiSafepayPayment
      - name: Run PHPunit
        working-directory: /tmp/shopware/custom/plugins/MltisafeMultiSafepayPayment
        run: ../../../vendor/bin/phpunit --coverage-clover=coverage.xml -c phpunit.xml.dist
      - name: Send clover to codecov
        working-directory: /tmp/shopware/custom/plugins/MltisafeMultiSafepayPayment
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -R .
